### ISSUE TITLE
"Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_doc#21]
I noticed that the "Edit on GitHub" link on the upper right of all the doc pages is broken (since the move?)
I don't know how to fix it, though. Where is the info stored?

Example, link is
```https://github.com/tripal/t4d8/blob/9.x-4.x/docs/index.rst```
Link should be
```https://github.com/tripal/tripal_doc/blob/4.x/docs/index.rst```

**Comment by laceysanderson** [comment]
Hmmm 🤔 I would check in the config files in the root docs folder for this.

**Comment by dsenalik** [comment]
Okay, the "new" docs at
https://tripaldoc.readthedocs.io/en/latest/
are fine. I was at the "old" site
https://tripal4.readthedocs.io/en/latest/

There is one place in the "new" docs that references this old url, I can do a pull request for that and then close this issue.

**Comment by dsenalik** [comment]
Pull request https://github.com/tripal/tripal_doc/pull/23

**Comment by dsenalik** [comment]
Oops, I forgot to close this. 🙈
