### ISSUE TITLE
Naming conventions for Fields

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_doc#27]
During the in-person PAG-adjacent Cofest in 2023, we came up with a few naming conventions for field-related files.

[Google Docs notes](https://docs.google.com/document/d/1oKqSDJpk1OtoyrX0Fp-10ltghpat8W_Bze1Tdegb2Jk/edit# "Google Docs notes")

Using these conventions, we walked through creating a brand new field, so it is probably safe to commit these conventions now.

**Comment by laceysanderson** [comment]
Adding in comments from after the above PR was merged:

> These naming conventions are good for core Tripal fields. The word "Default" in the naming conventions should be clarified. It's for core fields, whereas fields in extension modules probably shouldn't use the word "Default"

> It does say "In addition, for fields that will be included in Tripal Core, note the ‘Default’ designation" currently but we could do another PR to make sure it is really clear (especially for anyone who doesn't read the text but just jumps in to look at the table as a reminder.

I'm leaving the issue open so we remember to update this naming doc with this clarification.

**Comment by Ferrisx4** [comment]
Fixed by #53
