### ISSUE TITLE
Upgrading the Tripal 3 docs surrounding building a site to Tripal 4

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal_doc#49]
Fill out the Building your Site section by transferring over the info from the Tripal 3 docs with updated screenshots and text where things have changed focusing on [Brief Drupal Overview](https://tripal.readthedocs.io/en/latest/user_guide/drupal_overview.html), [Learn Chado](https://tripal.readthedocs.io/en/latest/user_guide/learn_chado.html) (this will be identical), [Working with Content Types](https://tripal.readthedocs.io/en/latest/user_guide/content_types.html), [Setup of an Example Site](https://tripal.readthedocs.io/en/latest/user_guide/example_genomics.html).

**Comment by laceysanderson** [comment]
We will want to add the "Setup of an Example Site" under "Building your site" in the new documentation. Specifically:

- Building your Site
   - Example Setup of a Genomic Site
      - Organisms
      - Analyses
      - Cross References (currently no UI for this 😢 )
      - Controlled Vocabularies
      - Genomes and Genes
      - Importing Publications (in PR)
      - Functional Annotation (won't be upgraded for awhile so leave this out entirely)

For the database references it might be best to show them how to add it via an SQL statement 🤔

**Comment by Ferrisx4** [comment]
Was work done on this around or since the San Diego Cofest? I seem to remember something but can't find anything. If not, I'll assign myself and take a crack at it.

**Comment by spficklin** [comment]
None that I know of.

**Comment by laceysanderson** [comment]
Yes, @pdtouch as been working on it :-) It looks like the updates have been added into the PR for the user permissions docs though which may be why you didn't see it 🙈 It's in PR #52 if you want to take a look and give feedback on it?

**Comment by pdtouch** [comment]
[<a href=https://github.com/tripal/tripal_doc/pull/52>#52] has my comments as @laceysanderson mentioned.

**Comment by laceysanderson** [comment]
The genomic example is complete so this can be closed :-)
