### ISSUE TITLE
Scientific name(s) not italicized

### ISSUE THREAD

**Issue by csnizik** [tripal/tripal_doc#79]
I noticed two instances where a scientific name is not italicized. To adhere to standard scientific convention, these should be italicized.

Examples:

- _Citrus sinensis_ in `organisms.rst`
- _Citrus sinensis_ in `genomes_and_genes.rst`

I will also scan the files for any other non-italicized scientific names.

**Comment by csnizik** [comment]
I just realized that there is an open PR for typos, and _Citrus Sinensis_ is corrected (currently it is "sinesis") in that PR. I'll wait until it is merged before submitting a PR for this.

**Comment by laceysanderson** [comment]
Sounds good! Thanks @csnizik, that other PR has now been merged :-)
